#!/bin/sh
set -eu

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<EOSQL
DO \$\$
BEGIN
  IF NOT EXISTS (SELECT FROM pg_catalog.pg_roles WHERE rolname = '$N8N_DB_USER') THEN
    CREATE USER "$N8N_DB_USER" WITH PASSWORD '$N8N_DB_PASS';
  END IF;
END
\$\$;

SELECT 'CREATE DATABASE "$N8N_DB_DATABASE" OWNER "$N8N_DB_USER"'
WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = '$N8N_DB_DATABASE')\gexec

GRANT ALL PRIVILEGES ON DATABASE "$N8N_DB_DATABASE" TO "$N8N_DB_USER";
EOSQL
